<?php
/**
 * Created by PhpStorm.
 * User: chenyu
 * Date: 2019/2/9
 * Time: 9:04
 */

namespace App\Services\WechatOfficial\Receiver;


class MainReceiver extends AbstractReceiver
{

    public function handle($received_id, $wx_app_id, $openid, $type)
    {
        return parent::handle($received_id, $wx_app_id, $openid, $type); // TODO: Change the autogenerated stub
    }
}